import css from './style.module.scss'
import './globals.css'

import { Header } from '@/components/header'

import { Inter } from 'next/font/google'
import type { Metadata } from 'next'

import ReduxProvider from '@/store/redux.provider'
import { Controller } from './controller'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReduxProvider>
      <Controller />
      <html lang="pt-BR">
        <body className={`${inter.className} ${css["body"]}`}>
          <Header.Root>
            <Header.Logo />
          </Header.Root>

          {children}
        </body>
      </html>
    </ReduxProvider>
  )
}
